# Generated by Django 6.0 on 2026-01-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_remove_claimnote_claim_remove_claimnote_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.driver',),
        ),
    ]
