# Generated by Django 6.0.1 on 2026-01-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('manager', 'Manager'), ('client', 'Client'), ('driver', 'Driver')], default='agent', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
