# Generated by Django 6.0 on 2026-01-23 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_client_profile_user_driver_profile_and_more'),
        ('common', '0004_agent_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_user', to='common.agent'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_user', to='common.manager'),
        ),
    ]
