# Generated by Django 6.0 on 2026-01-24 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_agent_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Current Latitude'),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Current Longitude'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_location_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Location Update'),
        ),
        migrations.AddField(
            model_name='driver',
            name='location_accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Location Accuracy (meters)'),
        ),
    ]
