# Generated by Django 6.0 on 2026-01-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_user_role_alter_user_table'),
        ('common', '0003_remove_claimnote_claim_remove_claimnote_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_user', to='common.client'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_user', to='common.driver'),
        ),
        migrations.AddField(
            model_name='user',
            name='simple_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
