# Generated by Django 6.0.1 on 2026-02-02 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_agent_profile_user_manager_profile'),
        ('common', '0005_driver_current_latitude_driver_current_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to='common.agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to='common.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to='common.driver'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to='common.manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('manager', 'Manager'), ('client', 'Client'), ('driver', 'Driver')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='simple_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
