# Generated by Django 6.0 on 2026-01-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(default='operations', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
