# Generated by Django 6.0 on 2026-01-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerProfile',
        ),
    ]
